// AUTO-GENERATED by scripts/codegen/export_api_contracts.py
// Source: src/services/curation/class_sources.py (CLASS_SOURCE_ROLES)
// DO NOT EDIT BY HAND: edit the Python source and re-run
// `python3 scripts/codegen/generate_contracts.py`.

/**
 * Every role a class_source value can have. The concrete class_source ids
 * are deployment-specific: fetch them from GET {prefix}/class_sources and
 * switch on `role`, never on the id.
 */
export const CLASS_SOURCE_ROLES = [
  'proposal',
  'low_conf',
  'model',
  'vlm',
  'vlm_unmatched',
  'vlm_new_class_pending',
  'vlm_reclassified',
  'cluster',
  'human',
  'merge',
  'label_import',
] as const;

export type ClassSourceRole = (typeof CLASS_SOURCE_ROLES)[number];

/** One entry of GET {prefix}/class_sources. */
export interface ClassSourceEntry {
  id: string;
  label: string;
  role: ClassSourceRole;
  short_label: string;
}
