// AUTO-GENERATED by scripts/codegen/export_api_contracts.py
// Source: src/routers/curation/_item_models.py (ItemDoc), src/services/curation/wire.py
// DO NOT EDIT BY HAND: edit the Python source and re-run
// `python3 scripts/codegen/generate_contracts.py`.

export interface ItemTextLine {
  text: string | null;
  box_norm: number[] | null;
  confidence: number | null;
  rel_height: number | null;
}

/**
 * The wire item every item-returning curation endpoint emits. Every key is
 * always present; a missing stored value is sent as null or the default.
 */
export interface ItemWire {
  id: string;
  crop_id: string;
  image_id: string;
  image_path: string;
  source_image_path: string;
  bbox_norm: number[];
  class_id: number | null;
  class_name: string | null;
  class_source: string | null;
  confidence: number;
  class_confidence: number | null;
  class_confidence_source: string | null;
  label_source: string | null;
  label_validated: boolean;
  class_validated: boolean;
  class_detector: string | null;
  class_detector_version: string | null;
  class_labeled_at: string | null;
  class_labeler: string | null;
  vlm_confidence: string | null;
  vlm_class_attempted_at: string | null;
  vlm_class_empty_reason: string | null;
  vlm_raw_class: string | null;
  vlm_proposed_class_id: number | null;
  vlm_proposed_class_name: string | null;
  proposed_class_id: number | null;
  proposed_class_name: string;
  needs_new_class: boolean;
  needs_new_class_note: string | null;
  cluster_id: number | null;
  cluster_kind: string | null;
  cluster_distance: number | null;
  cluster_similarity: number | null;
  cluster_is_core: boolean | null;
  cluster_nearest_id: number | null;
  cluster_subid: string | null;
  class_excluded: boolean;
  excluded_reason: string | null;
  excluded_at: string | null;
  review_dismissed_at: string | null;
  source: string;
  test_holdout: boolean;
  crop_rank_in_image: number | null;
  crop_area_norm: number | null;
  blur_lap_ratio: number | null;
  proposal_name: string | null;
  probe_pred_class: unknown;
  probe_pred_class_id: number | null;
  probe_pred_entropy: number | null;
  probe_disagreement: boolean | null;
  probe_in_scope: boolean | null;
  probe_model_version: string | null;
  probe_actionable: boolean | null;
  mistakenness_score: number | null;
  mistakenness_method: string | null;
  mistakenness_version: string | null;
  mistakenness_scored_at: string | null;
  uniqueness_score: number | null;
  dup_group_id: unknown;
  dup_group_size: number | null;
  dup_is_representative: boolean | null;
  updated_at: string;
  thumbnail_url: string;
  region_status: string | null;
  region_reason: string | null;
  region_rejection_reason: string | null;
  region_validated: boolean | null;
  region_auto_confirmed: boolean | null;
  region_verified: boolean | null;
  region_verified_at: string | null;
  region_verifier: string | null;
  region_verifier_version: string | null;
  region_visible: boolean | null;
  region_detector_chain: string[] | null;
  region_detected_at: string | null;
  region_profile: string | null;
  region_profile_revision: number | null;
  region_class_id: number | null;
  region_label_source: string | null;
  region_pairing: unknown;
  region_skip_verify: boolean | null;
  region_boxes: Record<string, unknown>[];
  region_count: number;
  region_rejected_count: number;
  region_max_score: number | null;
  region_set_complete: boolean | null;
  region_revision: number;
  item_text_lines: ItemTextLine[];
}

export type ItemWireKey = keyof ItemWire;

export const ITEM_WIRE_KEYS = [
  'id',
  'crop_id',
  'image_id',
  'image_path',
  'source_image_path',
  'bbox_norm',
  'class_id',
  'class_name',
  'class_source',
  'confidence',
  'class_confidence',
  'class_confidence_source',
  'label_source',
  'label_validated',
  'class_validated',
  'class_detector',
  'class_detector_version',
  'class_labeled_at',
  'class_labeler',
  'vlm_confidence',
  'vlm_class_attempted_at',
  'vlm_class_empty_reason',
  'vlm_raw_class',
  'vlm_proposed_class_id',
  'vlm_proposed_class_name',
  'proposed_class_id',
  'proposed_class_name',
  'needs_new_class',
  'needs_new_class_note',
  'cluster_id',
  'cluster_kind',
  'cluster_distance',
  'cluster_similarity',
  'cluster_is_core',
  'cluster_nearest_id',
  'cluster_subid',
  'class_excluded',
  'excluded_reason',
  'excluded_at',
  'review_dismissed_at',
  'source',
  'test_holdout',
  'crop_rank_in_image',
  'crop_area_norm',
  'blur_lap_ratio',
  'proposal_name',
  'probe_pred_class',
  'probe_pred_class_id',
  'probe_pred_entropy',
  'probe_disagreement',
  'probe_in_scope',
  'probe_model_version',
  'probe_actionable',
  'mistakenness_score',
  'mistakenness_method',
  'mistakenness_version',
  'mistakenness_scored_at',
  'uniqueness_score',
  'dup_group_id',
  'dup_group_size',
  'dup_is_representative',
  'updated_at',
  'thumbnail_url',
  'region_status',
  'region_reason',
  'region_rejection_reason',
  'region_validated',
  'region_auto_confirmed',
  'region_verified',
  'region_verified_at',
  'region_verifier',
  'region_verifier_version',
  'region_visible',
  'region_detector_chain',
  'region_detected_at',
  'region_profile',
  'region_profile_revision',
  'region_class_id',
  'region_label_source',
  'region_pairing',
  'region_skip_verify',
  'region_boxes',
  'region_count',
  'region_rejected_count',
  'region_max_score',
  'region_set_complete',
  'region_revision',
  'item_text_lines',
] as const satisfies readonly ItemWireKey[];

/** Region-of-interest attributes (fixed wire names, whatever the storage names). */
export const REGION_WIRE_KEYS = [
  'region_status',
  'region_reason',
  'region_rejection_reason',
  'region_validated',
  'region_auto_confirmed',
  'region_verified',
  'region_verified_at',
  'region_verifier',
  'region_verifier_version',
  'region_visible',
  'region_detector_chain',
  'region_detected_at',
  'region_profile',
  'region_profile_revision',
  'region_class_id',
  'region_label_source',
  'region_pairing',
  'region_skip_verify',
] as const satisfies readonly ItemWireKey[];

export type RegionWireKey = (typeof REGION_WIRE_KEYS)[number];

/** Keys a specific endpoint adds on top of ItemWire. */
export const REVIEW_EXTRA_KEYS = [
  'reason',
] as const;
export const SEARCH_EXTRA_KEYS = [
  'semantic_score',
] as const;
export const TRAINING_CANDIDATE_EXTRA_KEYS = [
  'region_box_id',
  'selection_reason',
] as const;
