// AUTO-GENERATED by scripts/codegen/export_region_status_to_ts.py
// Source: src/config/region_state.py (RegionStatus enum)
// DO NOT EDIT BY HAND: edit the Python enum and re-run the codegen script.

export enum RegionStatus {
  PENDING_DETECTION = 'pending_detection',
  PENDING_VERIFICATION = 'pending_verification',
  DETECTED = 'detected',
  VERIFY_REJECTED = 'verify_rejected',
  NO_REGION_BOX = 'no_region_box',
  NO_REGION_VISIBLE = 'no_region_visible',
  DETECTION_FAILED = 'detection_failed',
  FALSE_POSITIVE = 'false_positive',
}

export type RegionStatusValue =
  | 'pending_detection'
  | 'pending_verification'
  | 'detected'
  | 'verify_rejected'
  | 'no_region_box'
  | 'no_region_visible'
  | 'detection_failed'
  | 'false_positive';

export const REGION_STATUS_VALUES: readonly RegionStatusValue[] = [
  'pending_detection',
  'pending_verification',
  'detected',
  'verify_rejected',
  'no_region_box',
  'no_region_visible',
  'detection_failed',
  'false_positive',
] as const;

export const TERMINAL_REGION_STATUSES: readonly RegionStatusValue[] = [
  'detected',
  'verify_rejected',
  'no_region_box',
  'no_region_visible',
  'detection_failed',
  'false_positive',
] as const;

export const PENDING_REGION_STATUSES: readonly RegionStatusValue[] = [
  'pending_detection',
  'pending_verification',
] as const;

export const HUMAN_WRITABLE_REGION_STATUSES: readonly RegionStatusValue[] = [
  'detected',
  'verify_rejected',
  'no_region_visible',
  'false_positive',
] as const;

export const REGION_STATUS_ROLE: Readonly<Record<RegionStatusValue, string>> = {
  pending_detection: 'pending',
  pending_verification: 'pending',
  detected: 'positive',
  verify_rejected: 'rejected',
  no_region_box: 'absent',
  no_region_visible: 'absent',
  detection_failed: 'failed',
  false_positive: 'false_positive',
};

export const CONFIRM_STATUS_VALUE: RegionStatusValue = 'detected';
export const REJECT_STATUS_VALUE: RegionStatusValue = 'no_region_visible';
export const FALSE_POSITIVE_STATUS_VALUE: RegionStatusValue = 'false_positive';
