// AUTO-GENERATED by openprocessor/scripts/codegen/export_plate_status_to_ts.py
// Source: openprocessor/src/config/plate_state.py (PlateStatus enum)
// DO NOT EDIT BY HAND — re-run the codegen script after editing the Python source.

export enum PlateStatus {
  PENDING_DETECTION = 'pending_detection',
  PENDING_VERIFICATION = 'pending_verification',
  DETECTED = 'detected',
  VERIFY_REJECTED = 'verify_rejected',
  NO_PLATE_BOX = 'no_plate_box',
  NO_PLATE_VISIBLE = 'no_plate_visible',
  DETECTION_FAILED = 'detection_failed',
  FALSE_POSITIVE = 'false_positive',
}

export type PlateStatusValue =
  | 'pending_detection'
  | 'pending_verification'
  | 'detected'
  | 'verify_rejected'
  | 'no_plate_box'
  | 'no_plate_visible'
  | 'detection_failed'
  | 'false_positive';

export const PLATE_STATUS_VALUES: readonly PlateStatusValue[] = [
  'pending_detection',
  'pending_verification',
  'detected',
  'verify_rejected',
  'no_plate_box',
  'no_plate_visible',
  'detection_failed',
  'false_positive',
] as const;
