"""Triton ``config.pbtxt`` writer for YOLO26 models.

The official Ultralytics + Triton guide
(https://docs.ultralytics.com/guides/triton-inference-server) recommends
the ONNX + TensorRT execution accelerator path: place an ONNX file at
``<model_repo>/<model_name>/1/model.onnx`` and let Triton JIT-compile
the engine on first load (cached for subsequent loads). We follow that
approach here.

Critical YOLO26 specifics:

* ``end2end=True`` is the default -> a single output tensor of shape
  ``(N, 300, 6)`` per batch row, where each row is
  ``[x1, y1, x2, y2, score, class_id]``. NMS is INTERNAL to the model
  forward pass.
* No ``EfficientNMS_TRT`` plugin (unlike the existing YOLO11 path).
* ``class_id`` is float-encoded; clients must cast to int. We avoid
  ``half=True`` on export so FP16 doesn't lose integer precision above
  2048 (Ultralytics issue #24428).
* Input is ``BCHW float32 RGB normalized to [0, 1]`` -- same as YOLO11.

The companion ``triton_promote`` service handles the orchestration
(checkpoint -> ONNX -> config.pbtxt -> labels.txt -> load); this module
is the pure config-template piece, separated for unit testing without
touching the file system.
"""

from __future__ import annotations

from dataclasses import dataclass


# Sensible defaults for YOLO26 deployment.
DEFAULT_INPUT_SIZE = 640
DEFAULT_MAX_BATCH = 8
# Per Ultralytics' published TensorRT guide: 3 GiB workspace, FP16 mode.
DEFAULT_TRT_WORKSPACE_BYTES = 3 * 1024 * 1024 * 1024
# YOLO26's end2end head emits a fixed top-300 detections per image.
YOLO26_TOPK = 300
# Last-axis fields are [x1, y1, x2, y2, score, class_id_as_float].
YOLO26_DET_DIMS = 6


@dataclass(frozen=True)
class Yolo26TritonConfig:
    """Inputs to the config template. Pydantic-light; keep it dependency-free."""

    model_name: str
    input_size: int = DEFAULT_INPUT_SIZE
    max_batch_size: int = DEFAULT_MAX_BATCH
    fp16: bool = True
    trt_workspace_bytes: int = DEFAULT_TRT_WORKSPACE_BYTES
    instance_count: int = 1
    # Triton GPU id list (NOT host CUDA_VISIBLE_DEVICES); usually [0].
    gpu_ids: tuple[int, ...] = (0,)


def render_config(cfg: Yolo26TritonConfig) -> str:
    """Render the full ``config.pbtxt`` string for a YOLO26 ONNX model.

    The file format is documented in Triton's protobuf schema; the
    snippet here matches the Ultralytics + Triton example in
    https://docs.ultralytics.com/guides/triton-inference-server with the
    YOLO26-specific output shape.

    Args:
        cfg: Bundle of model-specific options.

    Returns:
        The full ``config.pbtxt`` text. Caller writes it to disk.
    """
    if cfg.max_batch_size < 1:
        msg = f'max_batch_size must be >=1, got {cfg.max_batch_size}'
        raise ValueError(msg)
    if cfg.input_size <= 0:
        msg = f'input_size must be positive, got {cfg.input_size}'
        raise ValueError(msg)
    if not cfg.gpu_ids:
        msg = 'gpu_ids must contain at least one device'
        raise ValueError(msg)

    precision_mode = 'FP16' if cfg.fp16 else 'FP32'
    gpu_id_list = ', '.join(str(g) for g in cfg.gpu_ids)
    workspace = cfg.trt_workspace_bytes

    # Item 4 (fresh-start E2E findings 2026-09-25, round 2): this used to
    # be the bare '/models/cache' -- a SIBLING of every model directory
    # at the model repository root, not inside one. Triton's repository
    # index (GET /v2/repository/index, what the curation models/status
    # route and make models-list both read) enumerates every top-level
    # directory
    # under --model-store, so that path showed up as a bogus model named
    # "cache" with no config.pbtxt. Nesting it one level deeper, under
    # this model's own directory (a sibling of the numeric "1/" version
    # dir, which Triton's version scan ignores because it isn't an
    # integer), keeps the original intent -- a deletion of the model dir
    # cleans up its engine cache too, no cross-model pollution -- without
    # ever being a repo-root entry Triton's index can trip over.
    cache_path = f'/models/{cfg.model_name}/trt_cache'

    return f"""\
# Auto-generated by src/services/training/yolo_triton_config.py.
# Do not edit by hand; delete this file and re-run
# /curation/train/promote/{{job_id}} to regenerate.

name: "{cfg.model_name}"
backend: "onnxruntime"
max_batch_size: {cfg.max_batch_size}

input [
  {{
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, {cfg.input_size}, {cfg.input_size} ]
  }}
]

# YOLO26 end2end head — single output, NMS internal to the forward
# pass. Fields: [x1, y1, x2, y2, score, class_id]. class_id is
# float-encoded; cast to int in the client.
output [
  {{
    name: "output0"
    data_type: TYPE_FP32
    dims: [ {YOLO26_TOPK}, {YOLO26_DET_DIMS} ]
  }}
]

instance_group [
  {{
    kind: KIND_GPU
    count: {cfg.instance_count}
    gpus: [ {gpu_id_list} ]
  }}
]

# Dynamic batching collapses concurrent single-image requests onto
# preferred batch sizes; ~5ms queue delay is a common latency/throughput
# trade-off for this class of model.
dynamic_batching {{
  preferred_batch_size: [ 4, {cfg.max_batch_size} ]
  max_queue_delay_microseconds: 5000
}}

# Triton compiles the ONNX to a TensorRT engine on first load and
# caches it under trt_engine_cache_path. This is per the official
# Ultralytics + Triton guide
# (https://docs.ultralytics.com/guides/triton-inference-server).
optimization {{
  execution_accelerators {{
    gpu_execution_accelerator: [
      {{
        name: "tensorrt"
        parameters {{ key: "precision_mode" value: "{precision_mode}" }}
        parameters {{ key: "max_workspace_size_bytes" value: "{workspace}" }}
        parameters {{ key: "trt_engine_cache_enable" value: "true" }}
        parameters {{ key: "trt_engine_cache_path" value: "{cache_path}" }}
      }}
    ]
  }}
}}
"""


def render_labels_file(class_id_to_name: dict[int, str]) -> str:
    """Render the ``labels.txt`` file: one class name per line, in id order.

    YOLO26 outputs class ids as floats in ``output0[..., 5]``; the
    ``/detect`` route's name lookup reads this file to map an id to a
    human-readable label. For a subset-trained model where the original
    registry ids were renumbered to ``0..N-1`` contiguous, the caller
    is responsible for passing the *renumbered* mapping.
    """
    if not class_id_to_name:
        return ''
    max_id = max(class_id_to_name.keys())
    lines: list[str] = []
    for i in range(max_id + 1):
        name = class_id_to_name.get(i, '')
        if not name:
            # Treat gaps as "unknown_<id>" so a misconfigured model
            # serving doesn't return a blank label.
            name = f'unknown_{i}'
        lines.append(name)
    return '\n'.join(lines) + '\n'


__all__ = [
    'DEFAULT_INPUT_SIZE',
    'DEFAULT_MAX_BATCH',
    'YOLO26_DET_DIMS',
    'YOLO26_TOPK',
    'Yolo26TritonConfig',
    'render_config',
    'render_labels_file',
]
