#!/usr/bin/env python3
"""Codegen: export the curation API's wire contracts for frontend consumers.

Writes, under ``contracts/`` (or ``--out-dir``):

* ``json/item_wire.json`` — the item wire key set (the shared
  ``serialize_item`` output, typed by the ``ItemDoc`` JSON schema), the
  ``region_*`` subset, and the per-endpoint extra keys.
* ``ts/itemWire.ts`` — the same as a TypeScript ``ItemWire`` interface
  plus ``ITEM_WIRE_KEYS`` / ``REGION_WIRE_KEYS`` const arrays.
* ``ts/classSources.ts`` — the ``class_source`` role vocabulary.
* ``openapi/curation.json`` — ``app.openapi()`` filtered to paths under
  ``CurationConfig.api_prefix`` plus only the components they reference.

These need the app import, so the script re-runs itself under the
project interpreter with a whitelisted environment (see
``_contract_runtime.py``); ``OP_*`` overrides in the caller's shell never
leak into the output. ``--check`` exits 1 if any committed file is stale
or missing (wired as a pre-commit hook).

Usage:

    python3 scripts/codegen/export_api_contracts.py            # regenerate
    python3 scripts/codegen/export_api_contracts.py --check    # drift check
    python3 scripts/codegen/export_api_contracts.py --only openapi --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any


sys.path.insert(0, str(Path(__file__).resolve().parent))
import _contract_runtime


if TYPE_CHECKING:
    from collections.abc import Callable


REPO_ROOT = _contract_runtime.REPO_ROOT
DEFAULT_OUT_DIR = REPO_ROOT / 'contracts'
SCRIPT_REL = 'scripts/codegen/export_api_contracts.py'

ITEM_WIRE_JSON = Path('json/item_wire.json')
ITEM_WIRE_TS = Path('ts/itemWire.ts')
CLASS_SOURCES_TS = Path('ts/classSources.ts')
OPENAPI_JSON = Path('openapi/curation.json')


def _ts_header(source: str) -> str:
    return (
        f'// AUTO-GENERATED by {SCRIPT_REL}\n'
        f'// Source: {source}\n'
        '// DO NOT EDIT BY HAND: edit the Python source and re-run\n'
        '// `python3 scripts/codegen/generate_contracts.py`.\n'
    )


def _dump_json(data: Any) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + '\n'


# --- item wire -------------------------------------------------------------


def _item_doc_model():
    from src.routers.curation._common import ItemDoc

    return ItemDoc


def _item_wire_facts() -> dict[str, Any]:
    from src.services.curation import wire

    model = _item_doc_model()
    keys = list(model.model_fields)
    if set(keys) != set(wire.ITEM_WIRE_KEYS):
        missing = sorted(set(wire.ITEM_WIRE_KEYS) - set(keys))
        extra = sorted(set(keys) - set(wire.ITEM_WIRE_KEYS))
        raise SystemExit(
            f'ItemDoc fields diverge from serialize_item keys: '
            f'missing from ItemDoc={missing}, not emitted by serialize_item={extra}'
        )
    return {
        'item_keys': keys,
        'region_keys': list(wire.REGION_WIRE_KEYS),
        'extra_keys': {
            'review': sorted(wire.REVIEW_EXTRA_KEYS),
            'search': sorted(wire.SEARCH_EXTRA_KEYS),
            'training_candidate': sorted(wire.TRAINING_CANDIDATE_EXTRA_KEYS),
        },
        'json_schema': model.model_json_schema(mode='serialization'),
    }


def render_item_wire_json(facts: dict[str, Any]) -> str:
    return _dump_json(
        {
            'generated_by': SCRIPT_REL,
            'source': {
                'model': 'src/routers/curation/_common.py:ItemDoc',
                'serializer': 'src/services/curation/wire.py:serialize_item',
            },
            'notes': (
                'Every item-returning endpoint emits exactly item_keys (all always '
                "present; nullable per json_schema), plus that endpoint's extra_keys. "
                'region_keys is the region-of-interest subset; region_thumbnail_url is '
                'a server-built URL, not a region attribute.'
            ),
            **facts,
        }
    )


_DEF_REF_PREFIX = '#/$defs/'
_TS_IDENT = re.compile(r'^[A-Za-z_$][A-Za-z0-9_$]*$')


def ts_type(schema: dict[str, Any], refs: set[str] | None = None) -> str:
    """TypeScript type for one JSON-schema node (the subset pydantic emits
    for ``ItemDoc``). Unknown shapes raise rather than guess.

    A ``#/$defs/<Name>`` reference renders as ``Name`` and, when ``refs``
    is given, records ``Name`` so the caller emits its interface.
    """
    if '$ref' in schema:
        ref = schema['$ref']
        name = ref[len(_DEF_REF_PREFIX) :] if ref.startswith(_DEF_REF_PREFIX) else ''
        if refs is None or not _TS_IDENT.match(name):
            raise ValueError(f'unsupported schema node for TS export: {schema}')
        refs.add(name)
        return name
    if 'allOf' in schema and len(schema['allOf']) == 1:
        return ts_type(schema['allOf'][0], refs)
    if 'anyOf' in schema:
        parts: list[str] = []
        for sub in schema['anyOf']:
            t = ts_type(sub, refs)
            if t not in parts:
                parts.append(t)
        return ' | '.join(parts)
    if 'prefixItems' in schema:
        return '[' + ', '.join(ts_type(s, refs) for s in schema['prefixItems']) + ']'
    kind = schema.get('type')
    if kind is None:
        if 'allOf' in schema or 'oneOf' in schema:
            raise ValueError(f'unsupported schema node for TS export: {schema}')
        return 'unknown'
    simple = {'string': 'string', 'integer': 'number', 'number': 'number'}
    simple.update({'boolean': 'boolean', 'null': 'null'})
    if kind in simple:
        return simple[kind]
    if kind == 'array':
        inner = ts_type(schema.get('items', {}), refs)
        return f'({inner})[]' if ' | ' in inner else f'{inner}[]'
    if kind == 'object':
        return 'Record<string, unknown>'
    raise ValueError(f'unsupported JSON schema type for TS export: {kind!r}')


def ts_interfaces(schema: dict[str, Any], roots: set[str]) -> list[str]:
    """``export interface`` blocks for every ``$defs`` entry reachable from
    ``roots`` (transitively), sorted by name. Keys follow the model's field
    order and are always present, matching what the serializers emit."""
    defs = schema.get('$defs', {})
    pending = set(roots)
    rendered: dict[str, list[str]] = {}
    while pending:
        name = pending.pop()
        if name in rendered:
            continue
        if name not in defs:
            raise ValueError(f'$ref to undefined $defs entry: {name}')
        found: set[str] = set()
        body = [f'export interface {name} {{']
        for key, prop in defs[name].get('properties', {}).items():
            body.append(f'  {key}: {ts_type(prop, found)};')
        body.append('}')
        rendered[name] = body
        pending |= found - set(rendered)
    lines: list[str] = []
    for name in sorted(rendered):
        lines.extend([*rendered[name], ''])
    return lines


def _ts_string_array(name: str, values: list[str], type_name: str | None = None) -> list[str]:
    suffix = f' satisfies readonly {type_name}[]' if type_name else ''
    lines = [f'export const {name} = [']
    lines.extend(f"  '{v}'," for v in values)
    lines.append(f'] as const{suffix};')
    return lines


def render_item_wire_ts(facts: dict[str, Any]) -> str:
    schema = facts['json_schema']
    props = schema['properties']
    refs: set[str] = set()
    fields = [f'  {key}: {ts_type(props[key], refs)};' for key in facts['item_keys']]
    lines = [
        _ts_header('src/routers/curation/_common.py (ItemDoc), src/services/curation/wire.py'),
        *ts_interfaces(schema, refs),
        '/**',
        ' * The wire item every item-returning curation endpoint emits. Every key is',
        ' * always present; a missing stored value is sent as null or the default.',
        ' */',
        'export interface ItemWire {',
    ]
    lines.extend(fields)
    lines.append('}')
    lines.append('')
    lines.append('export type ItemWireKey = keyof ItemWire;')
    lines.append('')
    lines.extend(_ts_string_array('ITEM_WIRE_KEYS', facts['item_keys'], 'ItemWireKey'))
    lines.append('')
    lines.append(
        '/** Region-of-interest attributes (fixed wire names, whatever the storage names). */'
    )
    lines.extend(_ts_string_array('REGION_WIRE_KEYS', facts['region_keys'], 'ItemWireKey'))
    lines.append('')
    lines.append('export type RegionWireKey = (typeof REGION_WIRE_KEYS)[number];')
    lines.append('')
    lines.append('/** Keys a specific endpoint adds on top of ItemWire. */')
    for endpoint, keys in facts['extra_keys'].items():
        lines.extend(_ts_string_array(f'{endpoint.upper()}_EXTRA_KEYS', keys))
    lines.append('')
    return '\n'.join(lines)


# --- class sources ---------------------------------------------------------


def render_class_sources_ts() -> str:
    from src.services.curation.class_sources import CLASS_SOURCE_ROLES

    lines = [
        _ts_header('src/services/curation/class_sources.py (CLASS_SOURCE_ROLES)'),
        '/**',
        ' * Every role a class_source value can have. The concrete class_source ids',
        ' * are deployment-specific: fetch them from GET {prefix}/class_sources and',
        ' * switch on `role`, never on the id.',
        ' */',
        *_ts_string_array('CLASS_SOURCE_ROLES', list(CLASS_SOURCE_ROLES)),
        '',
        'export type ClassSourceRole = (typeof CLASS_SOURCE_ROLES)[number];',
        '',
        '/** One entry of GET {prefix}/class_sources. */',
        'export interface ClassSourceEntry {',
        '  id: string;',
        '  label: string;',
        '  role: ClassSourceRole;',
        '  short_label: string;',
        '}',
        '',
    ]
    return '\n'.join(lines)


# --- OpenAPI ---------------------------------------------------------------


def _collect_refs(node: Any, out: set[str]) -> None:
    if isinstance(node, dict):
        ref = node.get('$ref')
        if isinstance(ref, str):
            out.add(ref)
        for value in node.values():
            _collect_refs(value, out)
    elif isinstance(node, list):
        for value in node:
            _collect_refs(value, out)


def filter_openapi(spec: dict[str, Any], prefix: str) -> dict[str, Any]:
    """Keep paths under ``prefix`` and the transitive closure of the
    components they reference; drop everything else."""
    prefix = prefix.rstrip('/')
    paths = {
        p: item
        for p, item in spec.get('paths', {}).items()
        if p == prefix or p.startswith(prefix + '/')
    }
    components = spec.get('components', {})
    kept: dict[str, dict[str, Any]] = {}
    pending: set[str] = set()
    _collect_refs(paths, pending)
    seen: set[str] = set()
    while pending:
        ref = pending.pop()
        if ref in seen:
            continue
        seen.add(ref)
        parts = ref.split('/')
        if len(parts) != 4 or parts[:2] != ['#', 'components']:
            raise ValueError(f'unsupported $ref in OpenAPI spec: {ref}')
        section, name = parts[2], parts[3]
        target = components[section][name]
        kept.setdefault(section, {})[name] = target
        _collect_refs(target, pending)
    return {
        'openapi': spec['openapi'],
        'info': {
            'title': f'{spec["info"]["title"]} curation API',
            # The app version is deliberately omitted so a release bump
            # doesn't register as contract drift; git history versions this file.
            'version': 'see git history',
            'description': (
                f'Generated by {SCRIPT_REL}: app.openapi() filtered to paths under '
                f'{prefix} and the components they reference.'
            ),
        },
        'x-api-prefix': prefix,
        'paths': paths,
        'components': kept,
    }


def render_openapi_json() -> str:
    from src.config import get_curation_config
    from src.main import app

    return _dump_json(filter_openapi(app.openapi(), get_curation_config().api_prefix))


# --- driver ----------------------------------------------------------------


def _render_item_wire() -> dict[Path, str]:
    facts = _item_wire_facts()
    return {ITEM_WIRE_JSON: render_item_wire_json(facts), ITEM_WIRE_TS: render_item_wire_ts(facts)}


GENERATORS: dict[str, Callable[[], dict[Path, str]]] = {
    'item-wire': _render_item_wire,
    'class-sources': lambda: {CLASS_SOURCES_TS: render_class_sources_ts()},
    'openapi': lambda: {OPENAPI_JSON: render_openapi_json()},
}


def render(only: list[str] | None = None) -> dict[Path, str]:
    """Render ``{relative path: text}`` for the selected generators."""
    out: dict[Path, str] = {}
    for name in only or list(GENERATORS):
        out.update(GENERATORS[name]())
    return out


def check(rendered: dict[Path, str], out_dir: Path) -> list[str]:
    """Problems (empty when in sync) for ``rendered`` against ``out_dir``."""
    problems = []
    for rel, text in sorted(rendered.items()):
        target = out_dir / rel
        if not target.exists():
            problems.append(f'{target} does not exist')
        elif target.read_text(encoding='utf-8') != text:
            problems.append(f'{target} is out of sync')
    return problems


def write(rendered: dict[Path, str], out_dir: Path) -> None:
    for rel, text in sorted(rendered.items()):
        target = out_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding='utf-8')
        sys.stdout.write(f'wrote {target}\n')


def run(out_dir: Path, *, check_only: bool, only: list[str] | None = None) -> int:
    rendered = render(only)
    if not check_only:
        write(rendered, out_dir)
        return 0
    problems = check(rendered, out_dir)
    if problems:
        sys.stderr.write('\n'.join(problems) + '\n')
        sys.stderr.write('re-run: python3 scripts/codegen/generate_contracts.py\n')
        return 1
    sys.stdout.write(f'{len(rendered)} API contract file(s) in sync\n')
    return 0


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--check', action='store_true', help='Do not write; exit 1 on drift.')
    parser.add_argument(
        '--out-dir',
        type=Path,
        default=DEFAULT_OUT_DIR,
        help='Contracts root to write/check (default: contracts/).',
    )
    parser.add_argument(
        '--only',
        action='append',
        choices=sorted(GENERATORS),
        help='Limit to one generator (repeatable).',
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not _contract_runtime.in_sandbox():
        child_argv = ['--out-dir', str(args.out_dir.resolve())]
        child_argv += ['--check'] if args.check else []
        for name in args.only or []:
            child_argv += ['--only', name]
        return _contract_runtime.reexec(Path(__file__).resolve(), child_argv)
    return run(args.out_dir, check_only=args.check, only=args.only)


if __name__ == '__main__':
    sys.exit(main())
