#!/usr/bin/env python3
"""Codegen: export the ``RegionStatus`` enum to a TypeScript module.

``src/config/region_state.py`` is the single source of truth for the
region-status strings the curation pipeline writes to OpenSearch and
returns over the API. A TypeScript frontend that switches on those
strings must not hand-copy them — a Python-side rename (e.g. the B2
``no_region_box`` / ``no_region_visible`` change) would otherwise drift
silently. This script renders the enum, a string-literal union type, the
ordered value list, the terminal / pending / human-writable subsets, each
status's role and the confirm / reject / false-positive values into one ``.ts``
file, and ``--check`` fails when the committed file is stale (wired as a
pre-commit hook).

Usage:

    # Regenerate the committed contract file
    python3 scripts/codegen/export_region_status_to_ts.py

    # Write into a frontend checkout instead
    python3 scripts/codegen/export_region_status_to_ts.py ../my-frontend/src/lib/regionStatus.ts

    # Drift check (exit 1 if regeneration would change the target)
    python3 scripts/codegen/export_region_status_to_ts.py --check
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
_SOURCE = REPO_ROOT / 'src' / 'config' / 'region_state.py'


def _load_region_state():
    # Load the module file directly rather than via ``src.config`` so the
    # pre-commit hook runs under a bare system python3: the package
    # ``__init__`` pulls in pydantic-settings and friends, region_state.py
    # itself needs only the stdlib.
    spec = importlib.util.spec_from_file_location('_region_state_codegen', _SOURCE)
    if spec is None or spec.loader is None:
        raise ImportError(f'cannot load {_SOURCE}')
    module = importlib.util.module_from_spec(spec)
    # @dataclass resolves string annotations through sys.modules.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


_region_state = _load_region_state()
RegionStatus = _region_state.RegionStatus
TERMINAL_STATUSES = _region_state.TERMINAL_STATUSES
PENDING_STATUSES = _region_state.PENDING_STATUSES
HUMAN_WRITABLE_STATUSES = _region_state.HUMAN_WRITABLE_STATUSES
REGION_STATUS_INFO = _region_state.REGION_STATUS_INFO

DEFAULT_TARGET = REPO_ROOT / 'contracts' / 'ts' / 'regionStatus.ts'

HEADER = (
    '// AUTO-GENERATED by scripts/codegen/export_region_status_to_ts.py\n'
    '// Source: src/config/region_state.py (RegionStatus enum)\n'
    '// DO NOT EDIT BY HAND: edit the Python enum and re-run the codegen script.\n'
)


def _members() -> list[tuple[str, str]]:
    return [(m.name, m.value) for m in RegionStatus]


def _subset(values: frozenset) -> list[str]:
    # Declaration order, not set order, so the output is deterministic.
    return [m.value for m in RegionStatus if m in values]


def _const_array(name: str, values: list[str]) -> list[str]:
    lines = [f'export const {name}: readonly RegionStatusValue[] = [']
    lines.extend(f"  '{v}'," for v in values)
    lines.append('] as const;')
    return lines


def render_ts() -> str:
    """Render the full TypeScript module text for the current enum."""
    members = _members()
    lines: list[str] = [HEADER.rstrip('\n'), '', 'export enum RegionStatus {']
    lines.extend(f"  {name} = '{value}'," for name, value in members)
    lines.append('}')
    lines.append('')
    lines.append('export type RegionStatusValue =')
    union = [f"  | '{value}'" for _, value in members]
    union[-1] += ';'
    lines.extend(union)
    lines.append('')
    lines.extend(_const_array('REGION_STATUS_VALUES', [v for _, v in members]))
    lines.append('')
    lines.extend(_const_array('TERMINAL_REGION_STATUSES', _subset(TERMINAL_STATUSES)))
    lines.append('')
    lines.extend(_const_array('PENDING_REGION_STATUSES', _subset(PENDING_STATUSES)))
    lines.append('')
    lines.extend(_const_array('HUMAN_WRITABLE_REGION_STATUSES', _subset(HUMAN_WRITABLE_STATUSES)))
    lines.append('')
    lines.append('export const REGION_STATUS_ROLE: Readonly<Record<RegionStatusValue, string>> = {')
    lines.extend(f"  {m.value}: '{REGION_STATUS_INFO[m].role}'," for m in RegionStatus)
    lines.append('};')
    lines.append('')
    for const in ('CONFIRM_STATUS', 'REJECT_STATUS', 'FALSE_POSITIVE_STATUS'):
        value = getattr(_region_state, const).value
        lines.append(f"export const {const}_VALUE: RegionStatusValue = '{value}';")
    lines.append('')
    return '\n'.join(lines)


def check(target: Path) -> tuple[bool, str]:
    """Return ``(in_sync, message)`` for ``target`` against the enum."""
    if not target.exists():
        return False, f'{target} does not exist; run without --check to generate it.'
    if target.read_text(encoding='utf-8') != render_ts():
        return False, (
            f'{target} is out of sync with src/config/region_state.py; '
            're-run scripts/codegen/export_region_status_to_ts.py'
        )
    return True, f'{target} is in sync'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        'target',
        nargs='?',
        type=Path,
        default=DEFAULT_TARGET,
        help=f'TypeScript file to write/check (default: {DEFAULT_TARGET.relative_to(REPO_ROOT)})',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Do not write; exit 1 if the target is missing or stale.',
    )
    args = parser.parse_args(argv)
    target: Path = args.target

    if args.check:
        ok, message = check(target)
        (sys.stdout if ok else sys.stderr).write(message + '\n')
        return 0 if ok else 1

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_ts(), encoding='utf-8')
    sys.stdout.write(f'wrote {target}\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
